behaviors:
  SeekerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256 
      buffer_size: 1000000
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.3
        gamma: 0.99
        encoding_size: 256
        learning_rate : 1e-3
      gail:
        strength: 0.7
        demo_path: D:\Unity projects\VR-Experience\VR-Slasher\ImitationModels\FinalDemo.demo
    # behavioral_cloning:
    #   strength: 0.3
    #   demo_path: D:\Unity projects\VR-Experience\VR-Slasher\ImitationModels\FinalDemo.demo
    max_steps: 2000000
    time_horizon: 64
    summary_freq: 2000